version: "3.9"

services:
  #####################
  # API GATEWAY
  #####################
  api-gateway:
    image: mechanic_service:latest
    container_name: "api-gateway"
    hostname: api-gateway
    command: [ 'sh', '-c', 'npm run ts-node --transpileOnly --files ./services/ApiService/src/index.ts' ]
    env_file:
      - build/environments/grpc.env
      - build/environments/production.env
    ports:
      - "443:3000"
      - "80:3000"
    restart: always
  #####################
  # VEHICLE-SERVICE
  #####################
  vehicle-service:
    image: mechanic_service:latest
    container_name: "vehicle-service"
    hostname: vehicle-service
    restart: always
    command: [ 'sh', '-c', 'npm run ts-node --transpileOnly --files ./services/VehicleService/src/vehicleService.ts' ]
    env_file:
      - build/environments/grpc.env
      - build/environments/production.env
  #####################
  # CLIENT SERVICE
  #####################
  client-service:
    image: mechanic_service:latest
    container_name: "client-service"
    hostname: client-service
    restart: always
    command: [ 'sh', '-c', 'npm run ts-node --transpileOnly --files ./services/ClientService/src/clientService.ts' ]
    env_file:
      - build/environments/grpc.env
      - build/environments/production.env
  #####################
  # REPAIR SERVICE
  #####################
  repair-service:
    image: mechanic_service:latest
    container_name: "repair-service"
    hostname: repair-service
    restart: always
    command: [ 'sh', '-c', 'npm run ts-node --transpileOnly --files ./services/RepairService/src/RepairService.ts' ]
    env_file:
      - build/environments/grpc.env
      - build/environments/production.env
  #####################
  # USER SERVICE
  #####################
  user-service:
    image: mechanic_service:latest
    container_name: "user-service"
    hostname: user-service
    restart: always
    command: [ 'sh', '-c', 'npm run ts-node --transpileOnly --files ./services/UserService/src/userService.ts' ]
    env_file:
      - build/environments/grpc.env
      - build/environments/production.env
  #####################
  # AUTH SERVICE
  #####################
  auth-service:
    image: mechanic_service:latest
    container_name: "auth-service"
    hostname: auth-service
    restart: always
    command: [ 'sh', '-c', 'npm run ts-node --transpileOnly --files ./services/AuthService/src/authService.ts' ]
    env_file:
      - build/environments/grpc.env
      - build/environments/production.env
