version: "3.9"

services:
  #####################
  # REDIS
  #####################git
  redis-server:
    container_name: redis
    hostname: redis
    restart: always
    build:
      context: db/redis/build
      dockerfile: redis.dockerfile
#    ports:
#      - "6379:6379"
    volumes:
      - ./db/redis/dump:/data
  #####################
  # MONGO DB
  #####################
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file:
      - ./build/environments/development.env
    ports:
      - "27018:27017"
  #####################
  # CYPRESS API
  #####################
  cypress:
    image: mechanic_service:dev
    container_name: cypress
    hostname: cypress
    command: [ 'sh', '-c', './build/wait-for/wait-for mongo:27017 -- npm run ts-node-dev --respawn --files ./tests/cypress-api/index.ts' ]
    ports:
      - "3001:3001"
    env_file:
      - build/environments/development.env
    volumes:
      - ./tests/cypress-api:/core/tests/cypress-api
  #####################
  # API GATEWAY
  #####################
  api-gateway:
    image: mechanic_service:dev
    command: [ 'sh', '-c', './build/wait-for/wait-for mongo:27017 -- npm run ts-node-dev --respawn --files ./services/ApiService/src/index.ts' ]
    volumes:
      - ./services/ApiService/src:/core/services/ApiService/src/
  #    - ./:/core/
    env_file:
      - build/environments/development.env
    ports:
      - "3000:3000"
 #####################
  # VEHICLE-SERVICE
  #####################
  vehicle-service:
    image: mechanic_service:dev
    command: [ 'sh', '-c', './build/wait-for/wait-for mongo:27017 -- npm run ts-node-dev --respawn --files ./services/VehicleService/src/vehicleService.ts' ]
    depends_on:
      - mongo
    volumes:
    # - ./:/core/
      - ./services/VehicleService/:/core/services/VehicleService/
    ports:
      - 50053:50050
    env_file:
      - build/environments/development.env
  #####################
  # CLIENT SERVICE
  #####################
  client-service:
    image: mechanic_service:dev
    command: [ 'sh', '-c', './build/wait-for/wait-for mongo:27017 -- npm run ts-node-dev --respawn --files ./services/ClientService/src/clientService.ts' ]
    depends_on:
      - mongo
    volumes:
      #- ./:/core/
      - ./services/ClientService/:/core/services/ClientService/
    ports:
      - 50054:50050
    env_file:
      - build/environments/development.env
  #####################
  # REPAIR SERVICE
  #####################
  repair-service:
    image: mechanic_service:dev
    command: [ 'sh', '-c', './build/wait-for/wait-for mongo:27017 -- npm run ts-node-dev --respawn --files ./services/RepairService/src/repairService.ts' ]
    depends_on:
      - mongo
    volumes:
    # - ./:/core/
      - ./services/RepairService/:/core/services/RepairService/
    ports:
      - 50055:50050
    env_file:
      - build/environments/development.env
  #####################
  # USER SERVICE
  #####################
  user-service:
    image: mechanic_service:dev
    depends_on:
      - mongo
    volumes:
      - ./services/UserService/src:/core/services/UserService/src/
    env_file:
      - build/environments/development.env
  #####################
  # AUTH SERVICE
  #####################
  auth-service:
    image: mechanic_service:dev
    command: [ 'sh', '-c', './build/wait-for/wait-for mongo:27017 -- ./build/wait-for/wait-for redis-server:6379 -- npm run ts-node-dev --respawn --files ./services/AuthService/src/authService.ts' ]
    depends_on:
      - mongo
      - redis-server
    volumes:
      - ./services/AuthService/src:/core/services/AuthService/src/
    env_file:
      - build/environments/development.env
