// source: Schema/VehicleEngineSchema.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.Schema.VehicleEngineSchema', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Schema.VehicleEngineSchema = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Schema.VehicleEngineSchema, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Schema.VehicleEngineSchema.displayName = 'proto.Schema.VehicleEngineSchema';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Schema.VehicleEngineSchema.prototype.toObject = function(opt_includeInstance) {
  return proto.Schema.VehicleEngineSchema.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Schema.VehicleEngineSchema} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Schema.VehicleEngineSchema.toObject = function(includeInstance, msg) {
  var f, obj = {
    engineSize: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    enginePower: jspb.Message.getFieldWithDefault(msg, 2, 0),
    engineType: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Schema.VehicleEngineSchema}
 */
proto.Schema.VehicleEngineSchema.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Schema.VehicleEngineSchema;
  return proto.Schema.VehicleEngineSchema.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Schema.VehicleEngineSchema} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Schema.VehicleEngineSchema}
 */
proto.Schema.VehicleEngineSchema.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setEngineSize(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setEnginePower(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEngineType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Schema.VehicleEngineSchema.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Schema.VehicleEngineSchema.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Schema.VehicleEngineSchema} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Schema.VehicleEngineSchema.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEngineSize();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getEnginePower();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getEngineType();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional double engine_size = 1;
 * @return {number}
 */
proto.Schema.VehicleEngineSchema.prototype.getEngineSize = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Schema.VehicleEngineSchema} returns this
 */
proto.Schema.VehicleEngineSchema.prototype.setEngineSize = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional int32 engine_power = 2;
 * @return {number}
 */
proto.Schema.VehicleEngineSchema.prototype.getEnginePower = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.Schema.VehicleEngineSchema} returns this
 */
proto.Schema.VehicleEngineSchema.prototype.setEnginePower = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string engine_type = 3;
 * @return {string}
 */
proto.Schema.VehicleEngineSchema.prototype.getEngineType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Schema.VehicleEngineSchema} returns this
 */
proto.Schema.VehicleEngineSchema.prototype.setEngineType = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


goog.object.extend(exports, proto.Schema);
